[package]
name = "rust-music-player"
version = "0.1.0"
authors = ["Hubert Lin <linhub15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.10.0"